### PR TITLE
Initial public version

### PR DESCRIPTION
**Pull request by jesper-friis**
Initial version on github

### CODE REVIEW

**Comment by francescalb** [comment]
1. mechanics is not added as submodule currently, but says so in README.md
2. the git clone submodule as written below did nt work for me, but this might be due to it being on a brnach that is not master, and might be fized autamitcallywhen merge has been accepted

"This repository include the correct version of the crystallography and
mechanics domain ontologies as a git submodules.  Hence, use the
following command when cloning this repository:

    git clone --recurse-submodules --shallow-submodules git@github.com:emmo-repo/domain-atomistic.git"

**Review by francescalb — APPROVED** [review]
Tested in Protege and reasoning needed just a few minutes. Looks good!

**Comment by ahashibon** [comment]
merging to master as all good per @francescalb

**Comment by francescalb** [comment]
Updated to emmo-1.0.0-alpha2

**Pull request merged**
